name: IOS Build Automation 🍏

on:
  workflow_dispatch:
    inputs:
      lane:
        description: "📦 Choose which Fastlane lane to run"
        required: true
        type: choice
        options:
          - testflight_qa          # Upload QA build to TestFlight
          - testflight_staging     # Upload Staging build to TestFlight
          - testflight_prod        # Upload Prod build to TestFlight
          - submit_appstore        # Submit latest Prod build to App Store

jobs:
  deploy:
    uses: ./.github/workflows/ci-ios.yml
    with:
      lane: ${{ github.event.inputs.lane }}
    # secrets:
    #   FASTLANE_API_KEY: ${{ secrets.FASTLANE_API_KEY }}
    #   MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
    #   SSH_KEY: ${{ secrets.SSH_KEY }}
