name: eas update development
on:
  push:
jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    
    steps:
      - name: 🏗 Setup repo
        uses: actions/checkout@v3

      - name: 🏗 Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: npm

      - name: 🏗 Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_PAT }}

      - name: 📦 Install dependencies
        run: npm install

      - name: 🚀 EAS Update
        id: eas_update
        run: |
          update_json=$(eas update --non-interactive --branch development --auto --json)
          echo "Update JSON: $update_json"
          
          update_id=$(echo "$update_json" | jq -r '.id')
          update_url="https://expo.dev/accounts/gudditinaganjaneyulu/projects/expo-project/updates/$update_id"
          qr_code_url="https://api.qrserver.com/v1/create-qr-code/?size=250x250&data=$update_url"

          echo "update_id=$update_id" >> $GITHUB_ENV
          echo "update_url=$update_url" >> $GITHUB_ENV
          echo "qr_code_url=$qr_code_url" >> $GITHUB_ENV

      - name: 📜 Add Update Summary
        run: |
          echo "## 🚀 Update Summary" >> $GITHUB_STEP_SUMMARY
          echo "- **Update URL**: [$update_url]($update_url)" >> $GITHUB_STEP_SUMMARY
          echo "- **QR Code:**" >> $GITHUB_STEP_SUMMARY
          echo "![$update_url]($qr_code_url)" >> $GITHUB_STEP_SUMMARY

      - name: 🔔 Send Notification to Slack
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{
            "text": "🚀 *EAS Update Completed!*",
            "attachments": [
              {
                "color": "#36a64f",
                "fields": [
                  {
                    "title": "Update URL",
                    "value": "'$update_url'",
                    "short": false
                  }
                ],
                "image_url": "'$qr_code_url'"
              }
            ]
          }' $SLACK_WEBHOOK
