name: EAS Build Development

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: 🏷 Setup repo
        uses: actions/checkout@v3

      - name: 🏷 Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: npm

      - name: 🏷 Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_PAT }}

      - name: 📞 Install dependencies
        run: npm install

      - name: 🏷 Start EAS Build
        id: eas_build
        run: |
          build_json=$(eas build --platform android --non-interactive --profile development --json)
          echo "Build JSON: $build_json"
          
          build_id=$(echo $build_json | jq -r '.[0].id')
          apk_url=$(echo $build_json | jq -r '.[0].artifacts.applicationArchiveUrl')
          build_url="https://expo.dev/accounts/${{ secrets.EXPO_ACCOUNT_NAME }}/projects/${{ secrets.EXPO_PROJECT_NAME }}/builds/$build_id"
          qr_code_url="https://api.qrserver.com/v1/create-qr-code/?size=250x250&data=$build_url"

          echo "build_id=$build_id" >> $GITHUB_ENV
          echo "apk_url=$apk_url" >> $GITHUB_ENV
          echo "build_url=$build_url" >> $GITHUB_ENV
          echo "qr_code_url=$qr_code_url" >> $GITHUB_ENV

      - name: 📌 Add Build Summary
        run: |
          echo "## 🚀 EAS Build Completed! ✅" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**🔗 Build URL:** [Click to View Build]($build_url)" >> $GITHUB_STEP_SUMMARY
          echo "**🤖 APK Download:** [Download APK]($apk_url)" >> $GITHUB_STEP_SUMMARY
          echo "![QR Code]($qr_code_url)" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "_Build completed on $(date)_" >> $GITHUB_STEP_SUMMARY

      - name: 🟢 Send Slack message on success
        if: success()
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        run: |
          MESSAGE="*\ud83d\ude80 Build Succeeded for the Project \`${{ secrets.EXPO_PROJECT_NAME }}\`!*"
          DETAILS="\ud83d\udd17 *Build URL:* <$build_url|Click to View Build>\n\ud83e\udd16 *APK Download:* <$apk_url|Download APK>"

          curl -X POST -H 'Content-type: application/json' \
            --data '{
              "text": "'"$MESSAGE"'\n'"$DETAILS"'",
              "attachments": [
                {
                  "text": "\ud83d\udcf7 *Scan QR Code to Access Build:*",
                  "image_url": "'"$qr_code_url"'"
                }
              ]
            }' $SLACK_WEBHOOK
