name: EAS Build

on:
  pull_request:
  workflow_dispatch:  # Allows manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 🏗 Setup repo
        uses: actions/checkout@v4

      - name: 🏗 Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: npm

      - name: Setup Expo
        uses: expo/expo-github-action@v8
        with:
          expo-version: latest
          eas-version: latest
          token: ${{ secrets.EXPO_PAT }}

      - name: 📦 Install dependencies
        run: npm install

      - name: 🚀 Build development profile and capture output
        id: eas_build
        run: |
          output=$(eas update --auto)
          echo "$output"
          # Extract the URL from the output (assuming it's the first URL in the log)
          url=$(echo "$output" | grep -oP 'https?://\S+')
          echo "Build URL: $url"
          echo "::set-output name=build_url::$url"

      - name: 🔗 Add build URL and QR code to workflow summary
        run: |
          echo "### EAS Build Result" >> $GITHUB_STEP_SUMMARY
          echo "[Build URL](${{ steps.eas_build.outputs.build_url }})" >> $GITHUB_STEP_SUMMARY
          echo "![QR Code](https://api.qrserver.com/v1/create-qr-code/?size=150x150&data=${{ steps.eas_build.outputs.build_url }})" >> $GITHUB_STEP_SUMMARY
